### ISSUE TITLE
Unexpected reponse 403 from https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json

### ISSUE THREAD

**Issue by Fluxyuwu** [juanmuscaria/NotSoLegacyWorkspace-Gradle-Groovy#2]
> Task :getVersionJson
Unexpected reponse 403 from http://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.json

> Task :getAssetsIndex FAILED
Unexpected reponse 403 from https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json

FAILURE: Build failed with an exception.

**Comment by juanmuscaria** [comment]
You can either manually change the forge gradle to something like https://github.com/anatawa12/ForgeGradle-1.2/
Or use GTNH buildscript https://github.com/GTNewHorizons/ExampleMod1.7.10
